const data = {
    products: [{
            _id: '1',
            name: 'Zini Slim Shirts',
            category: 'Shirts',
            image: '/images/slm1.jpg',
            price: 120,
            countInStock: 12,
            brand: 'Zini',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '2',
            name: 'Zini BB Shirts',
            category: 'Shirts',
            image: '/images/slm1.jpg',
            price: 320,
            countInStock: 17,
            brand: 'Zini',
            rating: 4.3,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '3',
            name: 'Zini Oxford Shirts',
            category: 'Shirts',
            image: '/images/slm1.jpg',
            price: 120,
            countInStock: 0,
            brand: 'Zini',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '4',
            name: 'Zini Showman Shirts',
            category: 'Shirts',
            image: '/images/slm1.jpg',
            price: 120,
            countInStock: 47,
            brand: 'Zini',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '5',
            name: 'Zini College Shirts',
            category: 'Shirts',
            image: '/images/slm1.jpg',
            price: 120,
            countInStock: 7,
            brand: 'Zini',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '6',
            name: 'Zini Gents Shirts',
            category: 'Shirts',
            image: '/images/slm1.jpg',
            price: 120,
            countInStock: 37,
            brand: 'Zini',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },

        {
            _id: '7',
            name: 'Zini Biz Shirts',
            category: 'Shirts',
            image: '/images/slm1.jpg',
            price: 450,
            countInStock: 10,
            brand: 'Zini',
            rating: 5.0,
            numReviews: 100,
            description: 'high quality product',
        },

    ],
};

export default data;